baseURL:https://philippine.netlify.app/
languageCode: en-us
title: Forty
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Have a look
    subtitle: |-
      Here is my portfolio websit.
    title: Hi, my name is Philippine
  blog: {}
  contact:
    address:
      - title: Address
        street: London Business school (LBS), Regent's park
        city: London, NW14SA
        country: United Kingdom
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: pbonnaud.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: no telephone number to disclose
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Philippine Bonnaud
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-github
        label: GitHub
        url: https://github.com/PhilippineBonnaud
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/philippine-bonnaud/
  image: ''
  name: Philippine Bonnaud
  navigation:
    links:
      - name: Main page
        url: '#'
      - name: About
        url: blogs/About
      - name: coding projects in R and Python
        url: blogslayer2
    title: My portfolio
  tiles:
    enable: yes
    showcase:
      - image: cvpic.jpg
        subtitle: A little more about me
        title: About
        url: blogs/About
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: have a look
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
