baseURL: https://philippine.netlify.app/
languageCode: en-us
title: Philippine
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Have a look
    subtitle: |-
     Welcome to my website 
    title: Hi, my name is Philippine
  blog: {}
  contact:
    address:
      - city: London, NNW14SA
        country: United Kindom
        street: Regent's Park
        title: ADRESS
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: pbonnaud.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: no telephone number to disclose
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Philippine Bonnaud
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-github
        label: GitHub
        url: https://github.com/PhilippineBonnaud
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/philippine-bonnaud/
  image: ''
  name: Philippine Bonnaud
  navigation:
    links:
      - name: Main page
        url: '#'
      - name: About
        url: blogs/About
      - name: Dynamic Coding projects in R
        url: blogs2
    title: My portfolio
  tiles:
    enable: yes
    showcase:
      - image: cvpic.jpg
        subtitle: A little more about me
        title: About
        url: blogs/About
      - image: cvdownload.jpg
        subtitle: take a look at my CV
        title: CV
        url: blogs/cvdownload
      - image: LBSlogo.jpg
        subtitle: what I study now
        title: London Business school MFA
        url: https://www.london.edu/masters-degrees/masters-in-financial-analysis
      - image: Spayr.jpg
        subtitle: Where I work now
        title: Spayr
        url: https://www.spayr.eu/
      - image: UCL.jpg
        subtitle: My Bachelor Degree
        title: UCL BSc Management Science
        url: https://www.ucl.ac.uk/prospective-students/undergraduate/degrees/management-science-bsc
      - image: FOF34.jpg
        subtitle: Anchoring Netlé's coffee production in the future of food
        title: Future of food project
        url: blogs/FOF34
      - image: Heart.jpg
        subtitle: Predicting the key determinants of heart disease
        title: Heart disease
        url: blogs/Heart
      - image: dissertefull.jpg
        subtitle: Utilising cloud computing technology to improve the data interoperability of french healthcare participants
        title: Cloud computing and healthcare 
        url: blogs/dissertefull
      - image: Doctolib.jpg
        subtitle: Strategic analysis of the development of Doctolib
        title: Strategic analysis of Doctolib
        url: blogs/Doctolib
      - image: USApres.jpg
        subtitle: Predicting the outcome of the USA presidential election
        title: USA presidential election analysis
        url: blogs/USApres
      - image: KNN.jpg
        subtitle: Building a KNN algorithm from scratch for asset management
        title: KNN algorithms and Finance
        url: blogs/KNN
      - image: BS.jpg
        subtitle: Analysing the drivers of women's financial behaviours
        title: Behavioural Science
        url: blogs/BS
        
  two:
    buttonText: See for yourself
    enable: yes
    subtitle: Here is a portfolio of some of my R projects in a dymanic setting
    title: Dynamic Coding projects in R 
    url: blogs2
    
